name: Run tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "build/**"
      - "src/**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          # Defaults to the reference of the GitHub event that triggered the
          # workflow.
          ref: "${{ github.event.inputs.deploy_ref }}"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"
          cache: "yarn"

      - name: Install yarn webapp dependencies
        run: yarn install --immutable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                ${{ runner.os }}-yarn-

      - name: Test
        run: make test
